[FakeRestApi project] - fix tests

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -36,9 +36,13 @@ jobs:
           java -version
 
       - name: Run Tests
-        run: ./gradlew clean test --no-daemon --console=plain --warning-mode=none --quiet || true
+        run: set +e
+          ./gradlew clean test --no-daemon --console=plain --warning-mode=none --quiet
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+          set -e
         env:
           LOG_LEVEL: INFO
+        continue-on-error: true
 
       - name: List Allure Results
         if: always()
@@ -68,3 +72,9 @@ jobs:
           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: allure-history
+
+      - name: Fail if Tests Failed
+        if: steps.run_tests.outputs.exit_code != '0'
+        run: |
+          echo "Gradle tests failed (exit code: ${{ steps.run_tests.outputs.exit_code }})"
+          exit 1
